### ISSUE TITLE
No support for time scales

### ISSUE THREAD

**Issue by michalvankodev** [jvanbruegge/d3-axis-hyperscript#1]
Hey,

Currently I am constructing a graph component with Cycle.js using mostly code from this library but rewriting it so it supports time scales as well.

Are you interested in supporting all types of scales in this generator?

**Comment by jvanbruegge** [comment]
Yes, please. Would be great to have a PR

**Comment by michalvankodev** [comment]
Could we come up with list of features that this library should support? When I was developing time based graph I had to bring much more d3 dependencies like `d3-time-format` `d3-format` and so.

**Comment by jvanbruegge** [comment]
I think matching the API of d3-scales should be possible with it's dependencies

**Comment by jvanbruegge** [comment]
This should be possible now with version 2.0. I think I got most of the bugs, bus still be careful
